"""db init

Revision ID: bdd35b28b0af
Revises: None
Create Date: 2016-07-05 10:45:19.782000

"""

# revision identifiers, used by Alembic.
revision = 'bdd35b28b0af'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('norms', sa.String(), nullable=True),
    sa.Column('residue_num', sa.Integer(), nullable=True),
    sa.Column('sale_total', sa.Integer(), nullable=True),
    sa.Column('storage_time', sa.DateTime(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_goods_product_id'), 'goods', ['product_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_goods_product_id'), table_name='goods')
    op.drop_table('goods')
    ### end Alembic commands ###
